name: onu_soyleyemiyoruz
description: "Taboo game written for mobile."

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # UI & Animation
  lottie: ^3.3.2
  flutter_svg: ^2.0.9

  # State & Utils
  provider: ^6.1.5+1
  uuid: ^4.5.2

  # Storage & Path
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3

  # Audio (FIXED)
  audioplayers: ^6.5.1

  # Share
  share_plus: ^12.0.1

  # Linking
  url_launcher: ^6.3.1

  # Ads & IAP
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.1.13
  games_services: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/image/
    - assets/lottie/team.json
    - assets/lottie/talk.json
    - assets/lottie/trophy.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/image/game_logo.png
  remove_alpha_ios: true
